services:
  - type: web
    name: parts-catalogue
    env: static
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "18"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html